source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'NetEaseMoive' do
pod 'Alamofire', '~> 3.1.2' 
pod 'SwiftyJSON', '~> 2.3.1'
pod 'Kingfisher', '~> 1.8.2'
pod 'ObjectMapper', '~> 1.0'
pod 'AlamofireObjectMapper', '~> 2.1'
end

